const color_shader_vert = [
"#version 300 es",
"#define attribute in",
"",
"in vec3 vPosition;",
"in vec4 vColor;",
"",
"out vec4 theColor;",
"",
"uniform mat4 modelViewMatrix;",
"uniform mat4 projMatrix;",
"uniform float time;",
"",
"void main() {",
"    //*****************************************",
"    //********* Vertex Calculations  **********",
"    //*****************************************",
"    ",
"    mat4 mvpMatrix = projMatrix * modelViewMatrix;",
"    vec3 newVertex;",
"    if (vPosition.x > 0.0 && vPosition.y > 0.0 && vPosition.z > 0.0) {",
"        newVertex = vPosition + 1.2 * (sin(time) + 1.0) / 2.0 - 0.2;",
"    }",
"    else {",
"        newVertex = vPosition;",
"    }",
"    gl_Position = mvpMatrix * vec4(newVertex, 1.0);",
"    theColor = vColor;",
"}",
].join("\n");